### ISSUE TITLE
Flux tower ran out of space - only a small amount of data visible in the /home/data directory

### ISSUE THREAD

**Issue by philrosenberg** [philrosenberg/instrument-log#24]
Flux tower gave an error about running out of space. The campaign data all appeared to be on the hard drive, but only a small amount of data was visible.

**Comment by philrosenberg** [comment]
Suspected some problem with mounting of the usb drive, causing the /home/data symlink to point somewhere on internal memory. This would quickly fill up and then once the drive fills up linux does lots of weird things. Might then have problems remounting or there might be problems mounting to a non-empty directory

**Comment by philrosenberg** [comment]
Spoke to Hannah in the field.

The USB drive was mounted to /mnt/usb_drive (or something similar), but the `ls -l` command showed that the /home/data symlink, appeared to be a directory rather than a symlink. It also showed we had only read permission on it. We did a `chmod 777 /home/data` which gave an error about no space. we deleted the contents of /home/data/ and I'm not sure if Hannah did anything else (such as recreating the symlink), but this seemed to fix it.

**Comment by handyhan** [comment]
To summerise - the main issue was that the symlink between the loggers /home/data directory had been lost. As Phil says the data of previous logging could be seen in /mnt/usbstorge/data, but this was not linked to /home/data so the latter dir only had space for part of one single small file.

To fix I applied `chmod uga+wrx /home/data`  and then removed the contents of /home/data and then further `rmdir /home/data`. Then re-created the symlink with `ln -sf /mnt/usbstorage/data /home/`. this solved the issue and logging ran as  expected

**Comment by philrosenberg** [comment]
Note I added this issue twice by mistake - see also #23
