### ISSUE TITLE
Flux tower network issue. 

### ISSUE THREAD

**Issue by lecjlg** [philrosenberg/instrument-log#31]
The interface eth1 didn't automatically come up on boot. 
We are not sure if this was because the ethernet cable wasn't present during boot? This need further testing. 

To  mend this we did the following. 
Plug in the cable to eth1 

`ifconfig eth1 up`

this brings up the adapter. 
 
Then 

`/etc/ini.d/networking restart`

now check ifconfig that the ip has been issued by dhcp

**Comment by philrosenberg** [comment]
Note that this required opening up the logger box and plugging into the LAN1 port which has a fixed IP address. To do this, set the IP address on a laptop to be 192.168.3.1 (the last number can be anything from 1-254 other than 127). Then ssh to 192.168.3.127.
